spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551408
    password: 110804

  # para rodar com o MariaDB
  #    url: jdbc:mariadb://localhost:3307/pizzaria?createDatabaseIfNotExist=true
  #    username: root
  #    password: root
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
      show-sql: true