spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551408
    password: 110804
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
      show-sql: false